#!/usr/bin/env php
<?php
/*
 * MIT License
 *
 * Copyright (c) 2025 machinateur
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

declare(strict_types=1);

use Machinateur\RedisInfo\RedisInfoApplication;

require_once __DIR__ . '/vendor/autoload_runtime.php';

if (false == \ini_get('short_open_tag')) {
    echo 'Required configuration "short_open_tag" has to be enabled!' . \PHP_EOL,
            'Use -d to supply such configuration from the command line.' . \PHP_EOL,
    \PHP_EOL;

    exit(1);
}

return static function (): RedisInfoApplication {
    if (\Phar::running(false)) {
        return new RedisInfoApplication(
                name:    APP_NAME,
                version: APP_VERSION,
        );
    }

    return new RedisInfoApplication();
};
